### ISSUE TITLE
How to remove the Grayscale convertion?

### ISSUE THREAD

**Issue by nandobfmv** [sushant10/HQ_Bot#108]
please, I want to use the image crop with natural colors.

**Comment by sushant10** [comment]
grayscale is for sending to OCR

**Comment by nandobfmv** [comment]
I know but, the trivia game that I play changed the color of the 3 answers that appears on the screen while the 10 seconds timers are ticking.  they modified the color to a light gray, that becomes white when the image is modified to black and white. So I executed Tesseract alone to convert a screen that I took without color modification, and got success. Tesseract alone was able to read all the text, even with colors.
So, to be able to read the answers again, during trivia, I need to remove this grayscale conversion.
