### ISSUE TITLE
Trackback Error

### ISSUE THREAD

**Issue by CChamper** [sushant10/HQ_Bot#12]
Receiving Error:
Traceback (most recent call last):
File "answer_bot.py", line 17, in <module>
from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

Went through installation, and receiving this.

**Comment by CChamper** [comment]
After some testing, it seems like Google-Search-API is causing it, as that module was never installed. When I do try to install it, however, it gives me an error code:

Command "python setup.py egg_info failed with error code 1 in /private/var/folders/;_/hzc4rwbj22d54r1yh4dl8trm0000gn/T/pip-build-gq0m9djd/Google-Search-API/"

**Comment by bobdummy** [comment]
Yeah, I'm getting the same issue. Did you find a solution?

**Comment by deviharisakthi** [comment]
Install using `pip install git+https://github.com/abenassi/Google-Search-API/`. This worked for me.

**Comment by sushant10** [comment]
@deviharisakthi  is right. Here's the link : https://github.com/abenassi/Google-Search-API/

Look at installation in readme in the link.
