### ISSUE TITLE
Could someone make a video tutorial?

### ISSUE THREAD

**Issue by Ayresia** [sushant10/HQ_Bot#128]
I'm having an hard time to making this working, i'd like to someone make an video tutorial it would help me and also the others that are having issues. I'm trying it to work in windows.

**Comment by HypeK1d** [comment]
i can help

**Comment by flipinbeast** [comment]
@HypeK1d could you make a Mac tutorial?

**Comment by regularlydrunk** [comment]
@HypeK1d help pls :(

**Comment by smittypicks** [comment]
@HypeK1d Can you help me install?

**Comment by psanjay1** [comment]
@HypeK1d can you help me install it?

**Comment by Tanayazard** [comment]
i have tried everything to make to try to run the bot, but nothing is working. I have downloaded a bunch of programs to try to make it work, but nothing is happening. I tried to make a clone of it to the GitHub desktop setup, but it is not working either. I would really appreciate it if someone were to make a windows tutorial on how to get the bot up and running. Thanks!
