### ISSUE TITLE
OpenCV runtime error

### ISSUE THREAD

**Issue by CChamper** [sushant10/HQ_Bot#14]
Keep getting this error, everything is up-to-date.

raceback (most recent call last):
  File "answer_bot.py", line 23, in <module>
    import cv2
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/cv2/cv2.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /usr/local/lib/python3.6/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.6/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib

**Comment by sushant10** [comment]
This is a open-CV problem and related to the OS your running. Make sure you have installed opencv correctly. 
Which OS are you running?

**Comment by CChamper** [comment]
Im on a VM running OS X 10.11

**Comment by sushant10** [comment]
I believe due to some incompatibilities of open-CV it has errors with older macOS and apple changing the clock get time definition. You might have to run it on MacOSX 10.12. 

How did you install OpenCV? Using `brew`?

**Comment by CChamper** [comment]
Yeah, it was installed using brew

**Comment by CChamper** [comment]
I will try and upgrade to 10.12 to see if that makes a difference!

**Comment by sushant10** [comment]
Then i think it is a problem with OS. After looking at many posts i dont know what the solution is other than running it on OS X 10.12 or else might be a VM specific problem

Sorry that im not sure, i hope you figure it out.

**Comment by CChamper** [comment]
The error was fixed when updating to OSX 10.12

**Comment by deviharisakthi** [comment]
@CChamper is the bot working for you now.
