### ISSUE TITLE
Issue with OCR

### ISSUE THREAD

**Issue by Taratata92** [sushant10/HQ_Bot#18]
Hi, I've installed all the required packages with pip3, I don't have any error message, but the answers proposed by CashShow are not "read" by the OCR. I precise that Vysor windows is at the left of the screen. 

![sans titre](https://user-images.githubusercontent.com/36973548/36918739-256e45e6-1e5b-11e8-8697-d3a8b8f185b0.png)

**Comment by sushant10** [comment]
It's because of the "Prize for this question is 150" , It works best for HQ. I'm gonna have to change the code to take two separate screenshots for question and options. The code doesnt expect the Prize for this question , sorry about that

**Comment by Taratata92** [comment]
no problem :) 
do you think it's complicated to modify ?

**Comment by Taratata92** [comment]
I still have the issue with your new version :(

**Comment by sushant10** [comment]
It's not i haven't gotten around to it.

**Comment by Taratata92** [comment]
Hello Sushant10, Any news for this issue ? thanks
