### ISSUE TITLE
No such file or directory: 'Data/settings.json'

### ISSUE THREAD

**Issue by enegronjr** [sushant10/HQ_Bot#26]
Whenever I run the code, I get this error:

C:\PythonPrograms>python answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 264, in <module>
    load_json()
  File "answer_bot.py", line 49, in load_json
    remove_words = json.loads(open("Data/settings.json").read())["remove_words"]
FileNotFoundError: [Errno 2] No such file or directory: 'Data/settings.json'

**Comment by Yazington** [comment]
How did you manage to get it working ?
