### ISSUE TITLE
brew install tesseract ??

### ISSUE THREAD

**Issue by 0bytedna** [sushant10/HQ_Bot#34]
brew install tesseract command error
'brew' is not recognized as an internal or external command,
operable program or batch file.

**Comment by yapal** [comment]
which os are u using

**Comment by GrahamCrack3r** [comment]
If you're on macOS look up how to install Homebrew.

**Comment by 0bytedna** [comment]
I'm on Windows.

**Comment by yapal** [comment]
go to below link and download tesseract for windows and install .Later add it to environment path.
https://github.com/UB-Mannheim/tesseract/wiki
