### ISSUE TITLE
Bot runs, but cant take screenshot?

### ISSUE THREAD

**Issue by MrBlaze9081** [sushant10/HQ_Bot#39]
So I can open the script and it runs, but when I press S and then Enter, it pops up with this

Traceback (most recent call last):
  File "answer_bot.py", line 342, in <module>
    keypressed = input(bcolors.WARNING +'\nPress s to screenshot live game, sampq to run against sample questions or q to quit:\n' + bcolors.ENDC)
  File "<string>", line 1, in <module>
NameError: name 's' is not defined

I am not sure, but I think it's saying that S is not bound to a line of code?
Someone please help

**Comment by TYlerGreeen** [comment]
I just asked a question also that you can probably help me with!! I keep getting an error about the 
"python setup.py egg_info" failed with error code 1 in a long folder location

**Comment by TYlerGreeen** [comment]
Collecting Google-Search-API (from -r requirements.txt (line 10))
  Using cached Google-Search-API-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mn/jk9w4z6s3xs9kvbmjb0ws_w00000gq/T/pip-build-wm46k06i/Google-Search-API/setup.py", line 15, in <module>
        with open("test_requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'test_requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mn/jk9w4z6s3xs9kvbmjb0ws_w00000gq/T/pip-build-wm46k06i/Google-Search-API/
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by TylerG00** [comment]
Alright I figured out how to get past this issue by using git+https://github.com/abenassi/Google-Search-API/ in the requirements.txt file
Now I'm just having a problem with the answers coming out all with 0

**Comment by TylerG00** [comment]
Also s should be tied to a line of code as you can see here
hile(1):
		keypressed = input(bcolors.WARNING +'\nPress s to screenshot live game, sampq to run against sample questions or q to quit:\n' + bcolors.ENDC)
		if keypressed == 's':
			get_points_live()
		elif keypressed == 'sampq':
			get_points_sample()
		elif keypressed == 'q':
			break
		else:
			print(bcolors.FAIL + "\nUnknown input" + bcolors.ENDC)

**Comment by TylerG00** [comment]
I fixed my issue, but I still have the issue in which the return answer comes up as 0 for each question except for 7 and 18
