### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by nolanplatt** [sushant10/HQ_Bot#4]
Hello,

I keep getting an error when running python3 answer_bot.py
I am positive I did everything correct and that it is cd'ed 

Screenshot:
![screen shot 2018-02-21 at 5 00 38 pm](https://user-images.githubusercontent.com/20466654/36514329-c496bbba-1728-11e8-8c15-b5f9c252e7ac.png)

**Comment by sushant10** [comment]
Hi,

Make sure your in the correct directory.
Type `ls` to list the contents of the directory your in or type `pwd` to check directory.
Make sure the repo is cloned

**Comment by nolanplatt** [comment]
@sushant10 Yes, I am in the correct directory and my directory is fine. Yeah, the repo is fine.

**Comment by sushant10** [comment]
Is answer_bot.py in the directory?

**Comment by nolanplatt** [comment]
Yes @sushant10

**Comment by sushant10** [comment]
I dont know why it wouldnt work if the anwer_bot.py is in the correct directory. Can you show a screenshot of what shows when `ls` or `pwd` is typed?

**Comment by nolanplatt** [comment]
Hi,
the directory works now but now when I run it I am getting errors with the module, so I tried installing requirments.txt again and get this error:
![screen shot 2018-02-22 at 9 16 34 am](https://user-images.githubusercontent.com/20466654/36553474-404b68a4-17b1-11e8-8543-f609b6210716.png)

**Comment by nolanplatt** [comment]
You have any idea?

**Comment by sushant10** [comment]
Sorry for that I spelt the package wrong change it from `buetifulsoup4` to ` beautifulsoup4`

**Comment by PoonamChohdhary1991** [comment]
i too have same problem
![capture](https://user-images.githubusercontent.com/36765468/36611972-3ee185de-18fb-11e8-87b5-6fb790ef129a.PNG)

**Comment by sushant10** [comment]
Do this

`pip3 install --upgrade setuptools`

If it's already up to date, check that the module ez_setup is not missing. If it is, then

`pip3 install ez_setup`
Then try again
