### ISSUE TITLE
No module named "Google"

### ISSUE THREAD

**Issue by nolanplatt** [sushant10/HQ_Bot#5]
When I run "python3 answer_bot.py"

I get this error:
![screen shot 2018-02-22 at 12 46 20 pm](https://user-images.githubusercontent.com/20466654/36563298-851fb8a0-17ce-11e8-9c02-4b82af360388.png)

**Comment by sushant10** [comment]
Are you sure you installed all modules? 
Particularly `Google-Search-API`

**Comment by nolanplatt** [comment]
@sushant10 Every time I try installing Google-Search-API or requirments.txt, I get this error:
![screen shot 2018-02-22 at 1 10 44 pm](https://user-images.githubusercontent.com/20466654/36564358-e32dfd00-17d1-11e8-87a2-58da5cebd5c4.png)
