### ISSUE TITLE
Cant Install OpenCv

### ISSUE THREAD

**Issue by Hd1440** [sushant10/HQ_Bot#56]
After i install the requirements.txt, i had to use pip3 install tesseract because the brew command didnt work. I'm new at this stuff forgive me. But after installing tesseract I tried to install OpenCV but it gives me this error:

Collecting opencv Could not find a version that satisfies the requirement opencv (from versions: ) No matching distribution found for opencv You are using pip version 9.0.1, however version 9.0.3 is available. You should consider upgrading via the 'python -m pip install --upgrade pip' command.

I'm not too sure what to do, please help.

**Comment by alvinthomas135** [comment]
The reason you're getting that error is because that not the name of the python package.  You have to use command "pip3 install opencv-python" to install.
