### ISSUE TITLE
Error While Running Bot

### ISSUE THREAD

**Issue by Hd1440** [sushant10/HQ_Bot#60]
So I installed all the packages that are needed however when I go to open a cmd in the HQ Bot folder to run it by using the line given --> python3 answer_bot.py it tells me that there is no such command as python3 so I just take out the 3 and then it gives me this error:

python answer_bot.py Traceback (most recent call last): File "answer_bot.py", line 17, in <module> import urllib.request as urllib2 ImportError: No module named request

Any help is appreciated.

**Comment by tanujyadav97** [comment]
replace utllib.request with urllib2 in import
and replace urllib.request() with urllib2.Request()

**Comment by Hd1440** [comment]
@tanujyadav97 
Sorry I am a bit confused, do you mean that I should just take out the "urllib.request as" in line 17? And I cannot find urllib.request() in the file to replace, what line is it?

**Comment by tanujyadav97** [comment]
@Hd1440 replace "import urllib.request as urllib2" with "import urllib2"

**Comment by Hd1440** [comment]
Alright thanks that worked @tanujyadav97
