### ISSUE TITLE
opencv problem

### ISSUE THREAD

**Issue by Kablamoo123** [sushant10/HQ_Bot#61]
Ok, so whenever i type in 'pip3 install opencv' this error message shows and i have no clue what it means or what i have to do. Anyone know what to do? Im on Windows 10.
![opencv](https://user-images.githubusercontent.com/37598308/38172118-4368dcfa-359e-11e8-9eb8-810eb8def559.PNG)

**Comment by tombets2424** [comment]
did you ever fix this??

**Comment by Kablamoo123** [comment]
Yea i did, you type pip3 install opencv-python
And it sold work

**Comment by tombets2424** [comment]
Thanks, it worked.
