### ISSUE TITLE
TypeError: argument 1 must be read-only bytes-like object, not bytearray

### ISSUE THREAD

**Issue by Oliood** [sushant10/HQ_Bot#96]
`Press s to screenshot live game, sampq to run against sample questions or q to quit:
s
[   =] Reading screen/usr/local/lib/python3.5/dist-packages/pyscreenshot/plugins/wxscreen.py:22: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  bmp = wx.EmptyBitmap(size[0], size[1])
/usr/local/lib/python3.5/dist-packages/pyscreenshot/plugins/wxscreen.py:26: wxPyDeprecationWarning: Call to deprecated item ImageFromBitmap. Use bitmap.ConvertToImage instead.
  myWxImage = wx.ImageFromBitmap(bmp)
[  ==] Reading screenTraceback (most recent call last):
  File "answer_bot.py", line 289, in <module>
    get_points_live()
  File "answer_bot.py", line 267, in get_points_live
    question,options=parse_question()
  File "answer_bot.py", line 120, in parse_question
    text = read_screen()
  File "answer_bot.py", line 78, in read_screen
    screen_grab(screenshot_file)
  File "answer_bot.py", line 69, in screen_grab
    im = Imagegrab.grab(bbox=(31,228,485,620))
  File "/usr/local/lib/python3.5/dist-packages/pyscreenshot/__init__.py", line 46, in grab
    return _grab(to_file=False, childprocess=childprocess, backend=backend, bbox=bbox)
  File "/usr/local/lib/python3.5/dist-packages/pyscreenshot/__init__.py", line 29, in _grab
    return run_in_childprocess(_grab_simple, imcodec.codec, to_file, backend, bbox, filename)
  File "/usr/local/lib/python3.5/dist-packages/pyscreenshot/procutil.py", line 33, in run_in_childprocess
    raise e

TypeError: argument 1 must be read-only bytes-like object, not bytearray
`

I receive this error when i run the screen capture.
Has anyone else come across this issue?

**Comment by martingoldthen** [comment]
I'm getting the same problem,anyone knows how to solve this?

**Comment by ZedeN1** [comment]
Same error:
https://pastebin.com/zJp9fech

Installing requirements gives:
https://pastebin.com/Lh84F209

`$ pip --version`
`pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)`
 
`$ python3 --version`
`Python 3.5.2`

Before install had to additionally install 
`apt-get install -y libgtk2.0-dev libgtk-3-dev libjpeg-dev libtiff-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libwebkitgtk-dev libwebkitgtk-3.0-dev python3-dev`

Running Linux Mint 18.3

Running sampq works fine and I get the answers.

**Comment by mvpossum** [comment]
This problem seems related to some error in pyscreenshot wrapper for wxwidget. A temporal fix is to change the backend, for example:
`im = Imagegrab.grab(bbox=(31,228,485,640), backend="imagemagick")`
